version: '3'
services:
  task-service:
    build: .
    image: colwellcoding/task-service
    ports:
      - "8085:8085"
    links:
      - "cc-netflix:eureka"
      - "mariadb:db"
    depends_on:
      - "cc-netflix"
      - "mariadb"
  cc-netflix:
    image: colwellcoding/cc-netflix
    ports:
      - "8761:8761"
  mariadb:
    build: ../mariadb/.
    image: colwellcoding/mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: task_service
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
