spring:
  application:
    name: task-service
  data:
    mongodb:
      host: mongo

server:
  port: 8085
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

